version: '3.8'

services:
  flaskapp:
    build: .
    restart: always
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=bookstore-db.cf1fxdnidxor.us-east-1.rds.amazonaws.com
      - MYSQL_USER= **********               
      - MYSQL_PASSWORD= **********
      - MYSQL_DATABASE=bookstore-db
    ports:
      - "5000:5000"
    networks:
      - bookstore_net

networks:
  bookstore_net:
