version: '3.8'

services:
  api-gateway:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - auth-service
      - catalog-service
      - transaction-service
    networks:
      - bookstore_net

networks:
  bookstore_net:
    external: true
