apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  type: NodePort
  selector:
    app: transaction-service
  ports:
    - port: 5003
      targetPort: 5003
      nodePort: 30503
